version: '3.8'
services:
  crud-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
